apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-python
  namespace: hello
spec:
  template:
    spec:
      containers:
        - image: docker.io/jonnyman9/hello-python
          env:
            - name: TARGET
              value: "Python"
