apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hello

images:
- name: quay.io/jkeam/hello-python
  digest: sha256:fdae78154ab971cb3beb6c4b0b33336d01606fefd9879448a909e2d7c5efedd0

resources:
  - namespace.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
