apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hello

images:
- name: quay.io/jkeam/hello-python
  digest: sha256:24f83ad5486ee0cdee99e61f74feb1e4539fe922f4b7fa3355ffb96110b7f796

resources:
  - namespace.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
